mdgrbfr:
	$(GPP) dg_rotate.cpp -o mdgrbfr.out -std=c++11 -ggdb -I$(PRMM)/include

mrbf:
	$(GPP) move_rbf.cpp -o mrbf.out -std=c++11 -ggdb -I$(PRMM)/include

mdgm:
	$(GPP) move_dgm.cpp -o mdgm.out -std=c++11 -ggdb -I$(PRMM)/include

mdgrbf1:
	$(GPP) move_dgrbf1.cpp -o mdgrbf1.out -std=c++11 -ggdb -I$(PRMM)/include

mdgrbf2:
	$(GPP) move_dgrbf2.cpp -o mdgrbf2.out -std=c++11 -ggdb -I$(PRMM)/include

dgms:
	g++ dg_ms_rotate.cpp -o dgms.out -std=c++11 -ggdb -I$(PRMM)/include
dgri:
	g++ dgrotinter.cpp -o dgri.out -std=c++11 -ggdb -I$(PRMM)/include
dgrims:
	g++ dgrotinterms.cpp -o dgrims.out -std=c++11 -ggdb -I$(PRMM)/include
