mmovel:
	g++ driver-lineal.cpp -o lin.out -std=c++11 -I/run/media/aditya/Data/include -ggdb
	
mmovef:
	g++ driver-farhat.cpp -o far.out -std=c++11 -I/run/media/aditya/Data/include -ggdb

mmovefw:
	g++-5 driver-farhat-wing.cpp -o farw.out -std=c++11 -I/media/aditya/Data/include -ggdb

mmovefwp:
	g++-5 driver-farhat-wing.cpp -o farwp.out -std=c++11 -I/media/aditya/Data/include -ggdb -fopenmp
