sq:
	$(GPP) rbf0_square.cpp -o sq.out -std=c++11 -ggdb -I$(GDR)/include
sqp:
	g++-5 rbf_square.cpp -o sqp.out -std=c++11 -ggdb -I/media/aditya/Data/include
wing:
	$(GPP) -o w.out -std=c++11 -ggdb -I../ rbf0_wing.cpp ../../bin/libarbf.a ../../bin/libalinalg.a ../../bin/libamatrix2.a