sq:
	$(GPP) rbf0_square.cpp -o sq.out -std=c++11 -ggdb -I$(GDR)/include
sqp:
	g++-5 rbf_square.cpp -o sqp.out -std=c++11 -ggdb -I/media/aditya/Data/include
wing:
	g++-5 rbf0_wing.cpp -o w.out -std=c++11 -ggdb -I/media/aditya/Data/include