OPTIONS = -std=c++11 -ggdb
dg3d:
	$(GPP) triangulate3d.cpp -o dg3d.out -I../../include/ $(OPTIONS)

dgmove:
	g++ dg_rotate.cpp -o dgrotate -std=c++11 -ggdb -I/media/aditya/Data/include

dgms:
	g++ dg_ms_rotate.cpp -o dgms.out -std=c++11 -ggdb -I/media/aditya/Data/include