metric2d:
	$(GPP) metric2d.cpp -o metric2d.out -std=c++11 -ggdb -I$(PRMM)/include

convert:
	$(GPP) convertformat.cpp -o convert.out -std=c++11 -ggdb -I$(PRMM)/include

q2t:
	$(GPP) convertQuadToTri.cpp -o q2t.out -std=c++11 -ggdb -I$(PRMM)/include
