skewmetric2d:
	$(GPP) skewmetric2d.cpp -o skewmetric2d.out -std=c++11 -ggdb -I$(PRMM)/include

shapemetric2d:
	$(GPP) shapemetric2d.cpp -o shapemetric2d.out -std=c++11 -ggdb -I$(PRMM)/include

convert:
	$(GPP) convertformat.cpp -o convert.out -std=c++11 -ggdb -I$(PRMM)/include

q2t:
	$(GPP) convertQuadToTri.cpp -o q2t.out -std=c++11 -ggdb -I$(PRMM)/include
